name: pokeapi_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  # Corregí el espaciado inválido
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  # Corregí el espaciado inválido
  flutter:
    sdk: flutter

  # Corregí el espaciado inválido
  http: ^1.2.1
  # Corregí el espaciado inválido
  flutter_svg: ^2.0.10+110
  # Corregí el espaciado inválido
  provider: ^6.1.2

  # Corregí el espaciado inválido
  cupertino_icons: ^1.0.8

dev_dependencies:
  # Corregí el espaciado inválido
  flutter_test:
    sdk: flutter

  # Corregí el espaciado inválido
  flutter_lints: ^4.0.0

  # Corregí el espaciado inválido
  flutter_launcher_icons: ^0.13.1

# The following section is specific to Flutter packages.
flutter:
  # Corregí el espaciado inválido
  uses-material-design: true

  # --- AÑADIDO ---
  # Esta sección le dice a Flutter que incluya tus imágenes de región.
  # Asegúrate de crear una carpeta 'assets' y dentro 'images'.
  assets:
    - assets/images/
  # --- FIN ---

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

# Esta es la configuración para tus iconos, está bien aquí.
flutter_launcher_icons:
  # Corregí el espaciado inválido
  android: "launcher_icon"
  ios: true
  image_path: "launcher_icon/poke-api-logo.png"
  min_sdk_android: 21